### ISSUE TITLE
Errors in Terra from terra-notebook-utils-tests

### ISSUE THREAD

**Issue by jordansafer** [DataBiosphere/terra-notebook-utils#385]
Hi! I'm an engineer on Terra, looking to investigate a minor issue.

Last Wednesday 4/6 at 11:10 EST (08:10 PST) we saw a good number of errors from the firecloud-cgl/terra-notebook-utils-tests workspace, from a caller trying to update entities in table "test-table-d281beea-6ffd-4d32-9478-d81daaecea1d" which didn't exist. The caller was bhannafi-service-account@ucsc-cgp-production.iam.gserviceaccount.com.

Is this expected behavior from terra-notebook-utils?

**Comment by DailyDreaming** [comment]
@jordansafer Tests appear to be passing currently (https://biodata-integration-tests.net/xbrianh/terra-notebook-utils/-/pipelines), so I assume that this was one of our engineers running tests locally.

@jessebrennan Were you working on this around that time?  ^

**Comment by jessebrennan** [comment]
Some more details would be helpful. What's a "good number"? AM or PM? I hadn't started working if it was AM.

**Comment by jordansafer** [comment]
Sure! 242 error from 08:10:15-8:10:23. And AM (24 hour times). I think we could close this issue, assuming it was just an engineer running tests locally. Just wanted to make sure nothing was broken/breaking from the spurt of errors!

**Comment by jessebrennan** [comment]
Ok! Thanks for the additional details. It will be good to have a record to compare against unless this crops up again.

Let's close, but repoen if this happens again.
