### ISSUE TITLE
The TNU drs info operation must not request the `accessUrl` 

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/terra-notebook-utils#391]
Currently the TNU drs info function requests the `accessUrl` by default, as shown here:
https://github.com/DataBiosphere/terra-notebook-utils/blob/060455919b3bfe770d3cdf7d7a45ff8b93d598c5/terra_notebook_utils/drs.py#L62-L82

This has two problems:

- It takes substantially longer to get the DRS info, as getting the signed URL requires an additional round-trip to the DRS server (including signed URL generation, etc.) which is not required when just getting the rest of the DRS info.

- More importantly, it means the DRS info (metadata) is only available if the user has access to the file. Users should be able to get the DRS info whether or not they have access to the file.

**Comment by mbaumann-broad** [comment]
I think the fix is relatively easy:

- Don't include accessUrl when getting DRS info by default

-Instead, change the `get_drs_info` and `get_drs` functions to have an optional parameter (list of strings) that are additional fields to include in the request. Then, pass ["accessUrl"] as the optional parameter value only in the case where the signed URL is needed.

**Comment by DailyDreaming** [comment]
Resolved by https://github.com/DataBiosphere/terra-notebook-utils/pull/392 .
