### ISSUE TITLE
TNU drs copy to local filesystem unnecessarily requests drs info (including accessUrl) twice

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/terra-notebook-utils#394]
The `_do_copy_drs` function unnecessarily calls `get_drs_info(drs_uri, access_url=True)` twice in the case of a copy to the local file system. A simple restructuring of the code should improve the efficiency and performance of this commonly used operation.
https://github.com/DataBiosphere/terra-notebook-utils/blob/522826525b63804e96832b8f57bdf85c6405c090/terra_notebook_utils/drs.py#L260-L273

**Comment by DailyDreaming** [comment]
Closed by #393.
